require("vim._core.ui2").enable({})
require("dashboard")
require("options")
require("keymaps")
require("commands")
require("pack")
require("treesitter")
require("lsp")

vim.cmd.colorscheme("gruvbox")
