local c = require("gruvbox.colors")

local M = {
  --See :h highlight-groups
  Boolean = { fg = c.bright_purple },
  Character = { fg = c.bright_purple },
  ColorColumn = { fg = c.none, bg = c.dark0 },
  Comment = { fg = c.dark3, italic = true },
  Conceal = { fg = c.purple },
  Conditional = { fg = c.purple },
  Constant = { fg = c.purple },
  Cursor = { fg = c.dark0, bg = c.bright_light0 },
  CursorColumn = { link = "CursorLine" },
  CursorIM = { link = "Cursor" },
  CursorLine = { fg = c.none, bg = c.bright_dark0 },
  CursorLineNr = { fg = c.bright_light0, bg = c.dark0, bold = true },
  Debug = { fg = c.bright_red },
  Define = { fg = c.cyan },
  Delimiter = { fg = c.light0 },
  Bracket = { fg = c.aqua },
  DiffAdd = { fg = c.bright_green, bg = c.dark0 },
  DiffChange = { fg = c.cyan, bg = c.dark0 },
  DiffDelete = { fg = c.bright_red, bg = c.dark0 },
  DiffText = { fg = c.bright_yellow, bg = c.dark0, reverse = true },
  Directory = { fg = c.bright_green, bold = true },
  EndOfBuffer = { fg = c.bright_dark0 },
  Error = { fg = c.bright_red, bg = c.dark0, bold = true, reverse = true },
  ErrorMsg = { fg = c.dark0, bg = c.bright_red, bold = true },
  Exception = { fg = c.bright_red },
  Float = { fg = c.bright_purple },
  FoldColumn = { fg = c.bright_dark0, bg = c.dark0 },
  Folded = { fg = c.bright_dark0 },
  Function = { fg = c.bright_green, bold = true },
  Identifier = { fg = c.bright_blue },
  Ignore = { link = "Conceal" },
  IncSearch = { fg = c.dark0, bg = c.light0 },
  Include = { fg = c.cyan },
  Keyword = { fg = c.bright_red },
  Label = { fg = c.bright_red },
  LineNr = { fg = c.light0 },
  Macro = { fg = c.cyan },
  MatchParen = { fg = c.none, bg = c.light0, bold = true, underline = true },
  ModeMsg = { fg = c.bright_yellow, bold = true },
  MoreMsg = { fg = c.bright_yellow, bold = true },
  NonText = { fg = c.bright_dark0 },
  Normal = { fg = c.bright_light0, bg = c.dark0 },
  NormalFloat = { link = "Normal" },
  Number = { fg = c.bright_purple },
  Operator = { fg = c.cyan },
  Pmenu = { fg = c.bright_light0, bg = c.bright_dark0 },
  PmenuExtra = { fg = c.light0, bg = c.bright_dark0 },
  PmenuExtraSel = { fg = c.bright_dark0, bg = c.bright_blue },
  PmenuKind = { fg = c.bright_red, bg = c.bright_dark0 },
  PmenuKindSel = { fg = c.bright_blue, bg = c.bright_blue },
  PmenuMatch = { fg = c.purple, bg = c.bright_dark0 },
  PmenuMatchSel = { fg = c.purple, bg = c.bright_blue, bold = true },
  PmenuSbar = { fg = c.none, bg = c.bright_dark0 },
  PmenuSel = { fg = c.dark0, bg = c.light0, bold = true },
  PmenuThumb = { fg = c.none, bg = c.light0 },
  PreCondit = { fg = c.cyan },
  PreProc = { fg = c.cyan },
  Question = { fg = c.yellow, bold = true },
  QuickFixLine = { fg = c.cyan, bg = c.dark0, reverse = true },
  Repeat = { fg = c.bright_red },
  Search = { fg = c.dark0, bg = c.light0 },
  SignColumn = { fg = c.bright_dark0, bg = c.dark0 },
  SnippetTabstop = { link = "Normal" },
  Special = { fg = c.yellow },
  SpecialChar = { fg = c.bright_red },
  SpecialComment = { fg = c.bright_red, italic = true },
  SpecialKey = { fg = c.bright_dark0 },
  SpellBad = { fg = c.bright_red, underline = true },
  SpellCap = { fg = c.bright_blue, underline = true },
  SpellLocal = { fg = c.cyan, underline = true },
  SpellRare = { fg = c.bright_purple, underline = true },
  Statement = { fg = c.bright_red },
  StatusLine = { fg = c.dark0, bg = c.bright_light0 },
  StatusLineNC = { link = "StatusLine" },
  StorageClass = { fg = c.yellow },
  String = { fg = c.bright_green },
  Structure = { fg = c.purple },
  TabLine = { fg = c.light0, bg = c.dark0 },
  TabLineFill = { fg = c.bright_light0, bg = c.dark0 },
  TabLineSel = { fg = c.bright_light0, bg = c.dark0, bold = true },
  Title = { fg = c.bright_green, bold = true },
  Todo = { fg = c.dark0, bg = c.light0, bold = true },
  ToolbarButton = { fg = c.bright_light0, bg = c.bright_dark0, bold = true },
  ToolbarLine = { fg = c.none },
  Type = { fg = c.bright_yellow },
  Typedef = { fg = c.bright_yellow },
  Underlined = { fg = c.bright_blue, underline = true },
  VertSplit = { fg = c.bright_dark0, bg = c.dark0 },
  Visual = { fg = c.dark0, bg = c.light0 },
  WarningMsg = { fg = c.bright_yellow, bold = true },
  WildMenu = { fg = c.bright_blue, bg = c.light0, bold = true },
  WinBar = { fg = c.bright_light0, bg = c.dark0 },
  WinBarNC = { fg = c.light0, bg = c.dark0 },

  --See :h diagnostic-highlights
  DiagnosticError = { bg = c.red },
  DiagnosticWarn = { bg = c.yellow },
  DiagnosticInfo = { bg = c.blue },
  DiagnosticHint = { bg = c.cyan },

  --See :h lsp-highlights
  LspInlayHint = { fg = c.light0 },

  --See :h treesitter-highlight-groups
  ["@boolean"] = { link = "Boolean" },
  ["@character"] = { link = "Character" },
  ["@character.special"] = { link = "SpecialChar" },
  ["@comment"] = { link = "Comment" },
  ["@conditional"] = { link = "Conditional" },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { link = "Special" },
  ["@constant.macro"] = { link = "Define" },
  ["@constructor"] = { link = "Special" },
  ["@debug"] = { link = "Debug" },
  ["@define"] = { link = "Define" },
  ["@exception"] = { link = "Exception" },
  ["@field"] = { link = "Identifier" },
  ["@float"] = { link = "Float" },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { link = "Special" },
  ["@function.macro"] = { link = "Macro" },
  ["@include"] = { link = "Include" },
  ["@keyword"] = { link = "Keyword" },
  ["@label"] = { link = "Label" },
  ["@macro"] = { link = "Macro" },
  ["@method"] = { link = "Function" },
  ["@namespace"] = { link = "Identifier" },
  ["@number"] = { link = "Number" },
  ["@operator"] = { link = "Operator" },
  ["@parameter"] = { link = "Identifier" },
  ["@preproc"] = { link = "PreProc" },
  ["@property"] = { link = "Identifier" },
  ["@punctuation.delimiter"] = { link = "Delimiter" },
  ["@punctuation.bracket"] = { link = "Bracket" },
  ["@repeat"] = { link = "Repeat" },
  ["@storageclass"] = { link = "StorageClass" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { link = "SpecialChar" },
  ["@string.special"] = { link = "SpecialChar" },
  ["@structure"] = { link = "Structure" },
  ["@tag"] = { link = "Tag" },
  ["@text.literal"] = { link = "Comment" },
  ["@text.reference"] = { link = "Identifier" },
  ["@text.title"] = { link = "Title" },
  ["@text.todo"] = { link = "Todo" },
  ["@text.underline"] = { link = "Underlined" },
  ["@text.uri"] = { link = "Underlined" },
  ["@type"] = { link = "Type" },
  ["@type.definition"] = { link = "Typedef" },
  ["@variable"] = { fg = c.bright_light0 },
  ["@keyword.function"] = { fg = c.bright_cyan },

  --See :h lsp-semantic-highlight
  ["@lsp.type.class"] = { link = "Structure" },
  ["@lsp.type.decorator"] = { link = "Function" },
  ["@lsp.type.enum"] = { link = "Constant" },
  ["@lsp.type.enumMember"] = { link = "Constant" },
  ["@lsp.type.function"] = { link = "Function" },
  ["@lsp.type.interface"] = { link = "Structure" },
  ["@lsp.type.macro"] = { link = "Macro" },
  ["@lsp.type.method"] = { link = "Function" },
  ["@lsp.type.namespace"] = { link = "Structure" },
  ["@lsp.type.parameter"] = { link = "Identifier" },
  ["@lsp.type.property"] = { link = "Identifier" },
  ["@lsp.type.struct"] = { link = "Structure" },
  ["@lsp.type.type"] = { link = "Type" },
  ["@lsp.type.typeParameter"] = { link = "TypeDef" },
  ["@lsp.type.variable"] = { link = "@variable" },

  --See telescope.nvim/plugin/telescope.lua
  TelescopeSelection = { link = "CursorLine" },
  TelescopeSelectionCaret = { link = "TelescopeSelection" },
  TelescopeMultiSelection = { link = "Type", default = true },
  TelescopeMultiIcon = { link = "TelescopePromptPrefix", default = true },
  TelescopePromptPrefix = { fg = c.bright_light0 },

  Attribute = { fg = c.bright_blue }, -- HTML attributes (e.g., class, id)
  Tag = { fg = c.bright_red },        -- Component tags
  TagBuiltin = { fg = c.orange },     -- Standard HTML elements (div, span)

  --See :h html
  htmlTag = { fg = c.bright_orange },
  htmlEndTag = { fg = c.bright_orange },
  htmlTagName = { fg = c.orange },
  htmlString = { fg = c.bright_green },
  htmlLink = { fg = c.bright_aqua, underline = true },

  tsxTag = { fg = c.bright_orange },
  tsxTagName = { fg = c.bright_orange },
  tsxComponentName = { fg = c.bright_yellow },
  tsxAttribute = { fg = c.bright_blue },

  vueRegion = { fg = c.fg },
  vueDirective = { fg = c.bright_aqua }, -- v-if, v-for, @click

  --See :h gitsigns-highlight-groups
  GitSignsAdd = { link = "DiffAdd" },
  GitSignsChange = { link = "DiffChange" },
  GitSignsDelete = { link = "DiffDelete" },
}

return M
